image: python:3.5.2-alpine

before_script:
  - pyvenv venv
  - source ./venv/bin/activate
  - python3 --version
  - pip install -U -r requirements.txt

cache:
  paths:
    - venv/
    - .cache/

stages:
  - test

test:
  stage: test
  script:
    py.test --cov=server/ --cov=common/ --cov=client/ tests/
